-- 1 Address table seed

DBCC CHECKIDENT ('Address', RESEED, 0)
GO

insert into Address (Country, State, StreetName, StreetNo) values ('United States', 'Kentucky', 'Russell', 7);
insert into Address (Country, State, StreetName, StreetNo) values ('United States', 'California', 'Park Meadow', '2');
insert into Address (Country, State, StreetName, StreetNo) values ('United States', 'Texas', 'Straubel', '56');
insert into Address (Country, State, StreetName, StreetNo) values ('United States', 'Tennessee', 'Drewry', '75968');
insert into Address (Country, State, StreetName, StreetNo) values ('United States', 'Nebraska', 'Banding', '8');
insert into Address (Country, State, StreetName, StreetNo) values ('United States', 'Louisiana', 'Ramsey', '78');
insert into Address (Country, State, StreetName, StreetNo) values ('United States', 'California', 'Truax', '6867');
insert into Address (Country, State, StreetName, StreetNo) values ('United States', 'California', 'Monica', '179');
insert into Address (Country, State, StreetName, StreetNo) values ('United States', 'Minnesota', 'Everett', '06');
insert into Address (Country, State, StreetName, StreetNo) values ('United States', 'New York', 'Longview', '785');

-- 2 Builder table seed

insert into Builder (BuilderName, Email) values ('Lemke-Huel', 'dsuttill0@vkontakte.ru');
insert into Builder (BuilderName, Email) values ('Murphy, Mann and Bogan', 'ssimonsson1@cnn.com');
insert into Builder (BuilderName, Email) values ('Rosenbaum and Sons', 'kslocumb2@jalbum.net');
insert into Builder (BuilderName, Email) values ('Ritchie, Gislason and Gleason', 'dmackleden3@cbsnews.com');
insert into Builder (BuilderName, Email) values ('Cartwright and Sons', 'lcurgenven4@nhs.uk');
insert into Builder (BuilderName, Email) values ('Steuber LLC', 'kondracek5@stanford.edu');
insert into Builder (BuilderName, Email) values ('Mosciski Group', 'dregnard6@icq.com');
insert into Builder (BuilderName, Email) values ('Volkman Group', 'jstanton7@unesco.org');
insert into Builder (BuilderName, Email) values ('O''Keefe-Wehner', 'ocharleston8@sciencedirect.com');
insert into Builder (BuilderName, Email) values ('Larkin LLC', 'tovernell9@pcworld.com');

-- 3 Project table seed


insert into Project (MinSqft, MaxSqft, Name, AddressId, BuilderId) values (376, 767, 'Arizona', 9, 6);
insert into Project (MinSqft, MaxSqft, Name, AddressId, BuilderId) values (416, 744, 'Hanover', 1, 9);
insert into Project (MinSqft, MaxSqft, Name, AddressId, BuilderId) values (373, 808, 'Harbort', 10, 5);
insert into Project (MinSqft, MaxSqft, Name, AddressId, BuilderId) values (381, 816, 'Crest Line', 3, 2);
insert into Project (MinSqft, MaxSqft, Name, AddressId, BuilderId) values (387, 710, 'Meadow Vale', 6, 3);
insert into Project (MinSqft, MaxSqft, Name, AddressId, BuilderId) values (406, 736, 'Buell', 8, 9);
insert into Project (MinSqft, MaxSqft, Name, AddressId, BuilderId) values (448, 723, 'Vermont', 10, 5);
insert into Project (MinSqft, MaxSqft, Name, AddressId, BuilderId) values (359, 811, 'Hagan', 7, 1);
insert into Project (MinSqft, MaxSqft, Name, AddressId, BuilderId) values (324, 817, 'Steensland', 8, 2);
insert into Project (MinSqft, MaxSqft, Name, AddressId, BuilderId) values (321, 850, 'Manitowish', 4, 9);
insert into Project (MinSqft, MaxSqft, Name, AddressId, BuilderId) values (422, 881, 'Gulseth', 1, 4);
insert into Project (MinSqft, MaxSqft, Name, AddressId, BuilderId) values (317, 714, 'Golf', 2, 8);
insert into Project (MinSqft, MaxSqft, Name, AddressId, BuilderId) values (414, 873, 'Magdeline', 6, 4);
insert into Project (MinSqft, MaxSqft, Name, AddressId, BuilderId) values (409, 775, 'Superior', 4, 1);
insert into Project (MinSqft, MaxSqft, Name, AddressId, BuilderId) values (426, 859, 'Killdeer', 8, 8);
insert into Project (MinSqft, MaxSqft, Name, AddressId, BuilderId) values (405, 823, 'Butterfield', 6, 1);
insert into Project (MinSqft, MaxSqft, Name, AddressId, BuilderId) values (327, 892, 'Swallow', 2, 8);
insert into Project (MinSqft, MaxSqft, Name, AddressId, BuilderId) values (350, 734, 'Corry', 9, 3);
insert into Project (MinSqft, MaxSqft, Name, AddressId, BuilderId) values (344, 757, 'Heffernan', 2, 5);
insert into Project (MinSqft, MaxSqft, Name, AddressId, BuilderId) values (398, 723, 'Loomis', 5, 10);

-- 4 Unit table seed

insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (586, 'erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede', 'neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl', 1, 6, 248, 68016, 10);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (643, 'lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis', 'arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget', 4, 1, 879, 65924, 18);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (505, 'sapien non mi integer ac neque duis bibendum morbi non quam nec', 'justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus', 4, 1, 367, 80780, 3);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (695, 'in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor', 'in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris', 1, 1, 331, 73754, 10);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (675, 'posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue', 'posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in', 4, 5, 422, 42554, 2);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (503, 'justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio', 'curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien', 4, 1, 176, 38142, 9);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (454, 'posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin', null, 6, 1, 103, 71080, 15);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (665, 'duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse', 'orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis', 2, 4, 233, 78984, 20);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (413, 'ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor', 'amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante', 2, 3, 887, 58638, 4);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (628, 'bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui', 'nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus', 5, 5, 313, 59600, 16);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (626, 'nec sem duis aliquam convallis nunc proin at turpis a', 'vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at', 3, 6, 177, 58029, 20);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (688, 'ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit', null, 2, 1, 167, 58100, 18);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (404, 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut', 'non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci', 1, 3, 362, 80601, 5);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (510, 'cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi', null, 4, 2, 404, 85450, 1);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (614, 'ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus', 'nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo', 1, 6, 738, 63862, 10);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (570, 'justo pellentesque viverra pede ac diam cras pellentesque volutpat dui', 'interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus', 4, 6, 675, 56083, 13);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (406, 'habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt', 'congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc', 1, 2, 523, 87092, 11);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (557, 'nulla neque libero convallis eget eleifend luctus ultricies eu nibh', 'consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus', 5, 2, 922, 72429, 3);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (658, 'ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar', 'augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea', 3, 3, 479, 79778, 13);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (513, 'velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros', 'morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem', 5, 2, 436, 53633, 18);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (405, 'tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante', null, 3, 5, 148, 83204, 20);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (416, 'leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa', null, 5, 2, 123, 64841, 9);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (654, 'tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in', 'rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo', 3, 3, 341, 69788, 15);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (506, 'lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna', 'nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim', 3, 2, 967, 46833, 2);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (634, 'id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo', null, 1, 5, 525, 78108, 20);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (579, 'nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt', 'vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra', 1, 4, 540, 53771, 14);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (551, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis', 2, 4, 339, 52427, 8);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (660, 'nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor', null, 1, 1, 395, 76611, 17);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (666, 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum', 'metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris', 4, 1, 533, 59002, 17);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (515, 'vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at', null, 4, 6, 452, 77044, 10);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (531, 'condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu', 'congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo', 3, 4, 890, 70127, 9);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (420, 'mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede', 'turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis', 1, 2, 666, 56103, 11);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (594, 'vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur', 'volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus', 5, 6, 812, 51304, 5);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (602, 'porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris', 'suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient', 6, 1, 613, 82442, 8);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (553, 'amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque', 'sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 5, 4, 535, 73590, 5);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (525, 'mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis', null, 1, 6, 239, 84118, 3);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (571, 'lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla', 'justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare', 6, 6, 869, 55418, 9);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (561, 'eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet', 'vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce', 4, 6, 714, 64569, 6);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (670, 'gravida nisi at nibh in hac habitasse platea dictumst aliquam augue', 'montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus', 1, 1, 365, 38146, 20);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (552, 'luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor', null, 6, 5, 570, 87702, 13);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (552, 'justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse', null, 3, 2, 533, 75281, 6);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (415, 'lacinia erat vestibulum sed magna at nunc commodo placerat praesent', 'fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa', 5, 6, 702, 52250, 16);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (406, 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus', 'ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', 5, 4, 597, 57762, 18);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (516, 'luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat', 'amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui', 4, 4, 352, 41426, 7);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (519, 'a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt', 'amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor', 6, 3, 356, 48364, 15);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (536, 'proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus', 'posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna', 5, 5, 536, 86911, 20);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (693, 'nulla tellus in sagittis dui vel nisl duis ac nibh fusce', 'elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus', 5, 1, 836, 60286, 13);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (603, 'id luctus nec molestie sed justo pellentesque viverra pede ac diam', 'molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae', 5, 5, 630, 59852, 15);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (433, 'ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies', null, 6, 1, 935, 82538, 17);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (523, 'imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere', null, 4, 6, 333, 43405, 4);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (614, 'ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio', 'ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper', 6, 4, 892, 74728, 13);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (523, 'nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie', 'aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo', 5, 3, 909, 64958, 20);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (572, 'metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque', 'justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales', 1, 1, 967, 43566, 8);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (663, 'habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum', null, 3, 1, 534, 52852, 7);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (528, 'ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat', 'tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque', 6, 1, 783, 48053, 14);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (628, 'aenean fermentum donec ut mauris eget massa tempor convallis nulla neque', 'non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel', 2, 1, 721, 65817, 7);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (677, 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis', 'ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit', 3, 5, 371, 69344, 16);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (453, 'penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum', 'suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget', 4, 5, 152, 48543, 19);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (452, 'ante nulla justo aliquam quis turpis eget elit sodales scelerisque', 'massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit', 6, 1, 863, 48770, 17);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (512, 'eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu', 'curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt', 6, 1, 776, 79311, 4);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (692, 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit', null, 2, 1, 499, 46769, 8);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (492, 'amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien', 'in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat', 1, 5, 812, 68638, 16);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (426, 'est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis', 'nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec', 5, 5, 792, 53879, 14);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (406, 'augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis', null, 3, 5, 262, 58137, 13);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (561, 'odio condimentum id luctus nec molestie sed justo pellentesque viverra', 'tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam', 4, 3, 570, 56469, 13);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (429, 'nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla', 'a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices', 1, 2, 470, 87375, 3);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (598, 'augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent', 'justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros', 2, 5, 408, 63025, 17);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (666, 'pede malesuada in imperdiet et commodo vulputate justo in blandit', 'amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec', 6, 6, 526, 54333, 1);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (620, 'libero ut massa volutpat convallis morbi odio odio elementum eu', 'rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper', 5, 2, 792, 55790, 1);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (695, 'integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis', null, 1, 3, 174, 63644, 20);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (442, 'duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu', null, 3, 6, 668, 55095, 5);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (687, 'mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id', 'aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse', 6, 6, 279, 77318, 17);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (564, 'non pretium quis lectus suspendisse potenti in eleifend quam a odio', 'pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra', 6, 6, 193, 82211, 13);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (608, 'quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum', null, 2, 1, 392, 59113, 8);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (425, 'nec dui luctus rutrum nulla tellus in sagittis dui vel', null, 4, 4, 703, 58120, 5);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (431, 'nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum', 'cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing', 5, 6, 467, 46814, 1);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (689, 'augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent', 'venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet', 1, 2, 967, 78050, 2);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (583, 'convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris', 'fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui', 5, 1, 113, 61851, 15);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (612, 'morbi non lectus aliquam sit amet diam in magna bibendum', 'pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi', 2, 2, 293, 60630, 11);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (545, 'elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis', 'ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices', 4, 2, 718, 39411, 17);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (592, 'aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur', 'porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet', 2, 5, 808, 71499, 19);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (502, 'nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti', null, 5, 3, 428, 52571, 8);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (689, 'dui luctus rutrum nulla tellus in sagittis dui vel nisl', 'mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh', 3, 6, 599, 38584, 1);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (631, 'primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus', null, 6, 4, 804, 78024, 14);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (688, 'ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed', 'consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus', 4, 1, 580, 40643, 8);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (424, 'nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel', null, 4, 4, 200, 87579, 7);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (570, 'adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien', null, 3, 6, 452, 60260, 9);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (523, 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus', 'tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in', 2, 5, 919, 61005, 14);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (659, 'sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus', 'sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo', 6, 1, 108, 38017, 1);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (573, 'dui luctus rutrum nulla tellus in sagittis dui vel nisl', null, 5, 6, 379, 68873, 4);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (411, 'magna bibendum imperdiet nullam orci pede venenatis non sodales sed', 'sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna', 6, 2, 487, 63079, 3);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (416, 'morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit', 'proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing', 2, 4, 815, 81252, 6);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (456, 'massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci', 'vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis', 4, 4, 753, 75050, 4);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (625, 'suspendisse ornare consequat lectus in est risus auctor sed tristique in', 'porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus', 4, 3, 581, 40639, 3);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (402, 'platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem', 'neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi', 1, 6, 363, 60983, 15);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (691, 'massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi', 'ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 3, 1, 942, 79533, 12);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (437, 'dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et', 'habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius', 1, 4, 914, 40158, 6);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (665, 'rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas', 'vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec', 5, 1, 712, 82477, 14);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (651, 'duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam', null, 2, 4, 935, 84057, 12);
insert into Units (FloorSpaceSqft, UnitDesc, AdditionalInfo, BedCount, BathCount, UnitNo, Price, ProjectId) values (434, 'malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit', 'lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem', 5, 6, 738, 79060, 18);